use crate::ast::{Block, Expr, Program, Stmt};
use anyhow::Context;

/// The MacroEngine performs a pre-compilation AST pass.
/// It detects `Expr::UseSchema`, downloads the corresponding compiler macro Wasm,
/// invokes the Wasm binary with the target URL, and replaces the AST node with 
/// the pure Turn AST generated by the macro.
pub struct MacroEngine;

impl MacroEngine {
    pub async fn expand(program: &mut Program) -> anyhow::Result<()> {
        let mut new_stmts = Vec::new();
        for stmt in &program.stmts {
            // Expand statements deeply
            let expanded_stmt = Self::expand_stmt(stmt.clone()).await?;
            new_stmts.push(expanded_stmt);
        }
        program.stmts = new_stmts;
        Ok(())
    }

    // Walks down the AST to find and expand expressions
    #[async_recursion::async_recursion]
    async fn expand_stmt(stmt: Stmt) -> anyhow::Result<Stmt> {
        match stmt {
            Stmt::Let { name, ty, init, is_persistent, span } => {
                let new_init = Self::expand_expr(init).await?;
                Ok(Stmt::Let { name, ty, init: new_init, is_persistent, span })
            }
            Stmt::Assign { target, value, span } => {
                let new_target = Self::expand_expr(target).await?;
                let new_value = Self::expand_expr(value).await?;
                Ok(Stmt::Assign { target: new_target, value: new_value, span })
            }
            Stmt::ContextAppend { expr, span } => {
                let new_expr = Self::expand_expr(expr).await?;
                Ok(Stmt::ContextAppend { expr: new_expr, span })
            }
            Stmt::Remember { key, value, span } => {
                let new_key = Self::expand_expr(key).await?;
                let new_value = Self::expand_expr(value).await?;
                Ok(Stmt::Remember { key: new_key, value: new_value, span })
            }
            Stmt::CallStmt { tool, arg, span } => {
                let new_tool = Self::expand_expr(tool).await?;
                let new_arg = Self::expand_expr(arg).await?;
                Ok(Stmt::CallStmt { tool: new_tool, arg: new_arg, span })
            }
            Stmt::ImplDef { type_name, methods, span } => {
                let mut new_methods = Vec::new();
                for m in methods {
                    new_methods.push(Self::expand_stmt(m).await?);
                }
                Ok(Stmt::ImplDef { type_name, methods: new_methods, span })
            }
            Stmt::Return { expr, span } => {
                let new_expr = Self::expand_expr(expr).await?;
                Ok(Stmt::Return { expr: new_expr, span })
            }
            Stmt::ExprStmt { expr, span } => {
                let new_expr = Self::expand_expr(expr).await?;
                Ok(Stmt::ExprStmt { expr: new_expr, span })
            }
            Stmt::Turn { body, span } => {
                Ok(Stmt::Turn { body: Self::expand_block(body).await?, span })
            }
            Stmt::If { cond, then_block, else_block, span } => {
                let new_cond = Self::expand_expr(cond).await?;
                let new_then = Self::expand_block(then_block).await?;
                let new_else = match else_block {
                    Some(b) => Some(Self::expand_block(b).await?),
                    None => None,
                };
                Ok(Stmt::If { cond: new_cond, then_block: new_then, else_block: new_else, span })
            }
            Stmt::While { cond, body, span } => {
                let new_cond = Self::expand_expr(cond).await?;
                let new_body = Self::expand_block(body).await?;
                Ok(Stmt::While { cond: new_cond, body: new_body, span })
            }
            Stmt::Match { expr, ok_binding, ok_block, err_binding, err_block, span } => {
                let new_expr = Self::expand_expr(expr).await?;
                let new_ok = Self::expand_block(ok_block).await?;
                let new_err = Self::expand_block(err_block).await?;
                Ok(Stmt::Match { expr: new_expr, ok_binding, ok_block: new_ok, err_binding, err_block: new_err, span })
            }
            Stmt::TestDef { name, mocks, body, span } => {
                let new_body = Self::expand_block(body).await?;
                Ok(Stmt::TestDef { name, mocks, body: new_body, span })
            }
            // StructDef and TypeAlias don't contain expressions
            other => Ok(other),
        }
    }

    #[async_recursion::async_recursion]
    async fn expand_block(block: Block) -> anyhow::Result<Block> {
        let mut new_stmts = Vec::new();
        for stmt in block.stmts {
            new_stmts.push(Self::expand_stmt(stmt).await?);
        }
        Ok(Block { stmts: new_stmts, span: block.span })
    }

    #[async_recursion::async_recursion]
    async fn expand_expr(expr: Expr) -> anyhow::Result<Expr> {
        match expr {
            Expr::UseSchema { protocol, url, span } => {
                Self::execute_wasm_macro(&protocol, &url, span.clone()).await
            }
            Expr::MethodCall { target, name, arg, span } => {
                Ok(Expr::MethodCall { target: Box::new(Self::expand_expr(*target).await?), name, arg: Box::new(Self::expand_expr(*arg).await?), span })
            }
            Expr::Recall { key, span } => Ok(Expr::Recall { key: Box::new(Self::expand_expr(*key).await?), span }),
            Expr::Call { name, arg, span } => Ok(Expr::Call { name: Box::new(Self::expand_expr(*name).await?), arg: Box::new(Self::expand_expr(*arg).await?), span }),
            Expr::Use { module, span } => Ok(Expr::Use { module: Box::new(Self::expand_expr(*module).await?), span }),
            Expr::Suspend { expected_type, msg, span } => Ok(Expr::Suspend { expected_type, msg: Box::new(Self::expand_expr(*msg).await?), span }),
            Expr::Spawn { expr, linked, monitored, span } => Ok(Expr::Spawn { expr: Box::new(Self::expand_expr(*expr).await?), linked, monitored, span }),
            Expr::SpawnRemote { node_id, closure, span } => Ok(Expr::SpawnRemote { node_id: Box::new(Self::expand_expr(*node_id).await?), closure: Box::new(Self::expand_expr(*closure).await?), span }),
            Expr::Ok(inner, span) => Ok(Expr::Ok(Box::new(Self::expand_expr(*inner).await?), span)),
            Expr::Err(inner, span) => Ok(Expr::Err(Box::new(Self::expand_expr(*inner).await?), span)),
            Expr::Send { pid, msg, span } => Ok(Expr::Send { pid: Box::new(Self::expand_expr(*pid).await?), msg: Box::new(Self::expand_expr(*msg).await?), span }),
            Expr::Trace { pid_expr, span } => Ok(Expr::Trace { pid_expr: Box::new(Self::expand_expr(*pid_expr).await?), span }),
            Expr::Vec { mut items, span } => {
                for i in &mut items { *i = Self::expand_expr(i.clone()).await?; }
                Ok(Expr::Vec { items, span })
            }
            Expr::Confidence { expr, span } => Ok(Expr::Confidence { expr: Box::new(Self::expand_expr(*expr).await?), span }),
            Expr::Budget { tokens, time, body, span } => {
                let new_tokens = match tokens { Some(t) => Some(Box::new(Self::expand_expr(*t).await?)), None => None };
                let new_time = match time { Some(t) => Some(Box::new(Self::expand_expr(*t).await?)), None => None };
                Ok(Expr::Budget { tokens: new_tokens, time: new_time, body: Self::expand_block(body).await?, span })
            }
            Expr::StructInit { name, fields, span } => {
                let mut new_fields = indexmap::IndexMap::new();
                for (k, v) in fields { new_fields.insert(k, Self::expand_expr(v).await?); }
                Ok(Expr::StructInit { name, fields: new_fields, span })
            }
            Expr::Index { target, index, span } => Ok(Expr::Index { target: Box::new(Self::expand_expr(*target).await?), index: Box::new(Self::expand_expr(*index).await?), span }),
            Expr::Turn { is_tool, params, ret_ty, body, span } => Ok(Expr::Turn { is_tool, params, ret_ty, body: Self::expand_block(body).await?, span }),
            Expr::Infer { target_ty, tools, body, driver, threshold, fallback, span } => {
                let new_tools = match tools {
                    Some(mut ts) => {
                        for t in &mut ts { *t = Self::expand_expr(t.clone()).await?; }
                        Some(ts)
                    }
                    None => None,
                };
                let new_body = Self::expand_block(body).await?;
                let new_driver = match driver { Some(d) => Some(Box::new(Self::expand_expr(*d).await?)), None => None };
                let new_threshold = match threshold { Some(t) => Some(Box::new(Self::expand_expr(*t).await?)), None => None };
                let new_fallback = match fallback { Some(b) => Some(Self::expand_block(b).await?), None => None };
                Ok(Expr::Infer { target_ty, tools: new_tools, body: new_body, driver: new_driver, threshold: new_threshold, fallback: new_fallback, span })
            }
            Expr::List { mut items, span } => {
                for i in &mut items { *i = Self::expand_expr(i.clone()).await?; }
                Ok(Expr::List { items, span })
            }
            Expr::Map { mut entries, span } => {
                for (_, v) in &mut entries { *v = Self::expand_expr(v.clone()).await?; }
                Ok(Expr::Map { entries, span })
            }
            Expr::Binary { op, left, right, span } => Ok(Expr::Binary { op, left: Box::new(Self::expand_expr(*left).await?), right: Box::new(Self::expand_expr(*right).await?), span }),
            Expr::Unary { op, expr, span } => Ok(Expr::Unary { op, expr: Box::new(Self::expand_expr(*expr).await?), span }),
            Expr::Paren(inner) => Ok(Expr::Paren(Box::new(Self::expand_expr(*inner).await?))),
            other => Ok(other),
        }
    }

    /// Mounts Wasmtime, fetches the Wasm Macro, passes the target URL, and returns the generated AST Block.
    async fn execute_wasm_macro(protocol: &str, url_expr: &Box<Expr>, span: crate::lexer::Span) -> anyhow::Result<Expr> {
        // 1. Evaluate the URL expression if it's a literal string
        let target_url = if let Expr::Literal { value: crate::ast::Literal::Str(s), .. } = &**url_expr {
            s.clone()
        } else {
            anyhow::bail!("use schema::{} Requires a literal string URL", protocol);
        };

        // Fetch the Wasm macro binary from the Turn registry or local cache
        let cache_dir = std::env::current_dir()
            .unwrap_or_else(|_| std::path::PathBuf::from("."))
            .join(".turn_cache")
            .join("macros");
            
        if !cache_dir.exists() {
            let _ = std::fs::create_dir_all(&cache_dir);
        }

        let wasm_cache_path = cache_dir.join(format!("{}_macro.wasm", protocol));
        let wasm_bytes = if wasm_cache_path.exists() {
            std::fs::read(&wasm_cache_path).unwrap_or_default()
        } else {
            // Check local development path first, fallback to remote HTTPS
            let local_dev_path = format!("macros/{}_adapter/target/wasm32-unknown-unknown/release/{}_macro.wasm", protocol, protocol);
            if std::path::Path::new(&local_dev_path).exists() {
                let bytes = std::fs::read(&local_dev_path).unwrap_or_default();
                let _ = std::fs::write(&wasm_cache_path, &bytes);
                bytes
            } else {
                let remote_url = format!("https://modules.turn-lang.dev/macros/{}_macro.wasm", protocol);
                println!("Turn Macro Engine: Fetching remote compiler macro from {} ...", remote_url);
                
                let client = reqwest::Client::new();
                match client.get(&remote_url).send().await {
                    Ok(resp) if resp.status().is_success() => {
                        let bytes = resp.bytes().await.unwrap_or_default().to_vec();
                        if !bytes.is_empty() {
                            let _ = std::fs::write(&wasm_cache_path, &bytes);
                        }
                        bytes
                    }
                    _ => vec![] // Will trigger bail below
                }
            }
        };

        use wasmtime::*;
        let engine = Engine::default();

        if wasm_bytes.is_empty() {
             anyhow::bail!("Could not load Wasm Macro for protocol '{}'. Ensure it is compiled locally or available at modules.turn-lang.dev", protocol);
        }

        let module = Module::new(&engine, &wasm_bytes)
            .context("Failed to compile macro Wasm")?;

        let mut store = Store::new(&engine, ());
        let instance = Instance::new(&mut store, &module, &[])
            .context("Failed to instantiate macro Wasm")?;

        let memory = instance
            .get_memory(&mut store, "memory")
            .context("Wasm module must export 'memory'")?;

        let allocate = instance
            .get_typed_func::<u32, u32>(&mut store, "allocate_memory")
            .context("Wasm module must export 'allocate_memory' fn")?;

        let deallocate = instance
            .get_typed_func::<(u32, u32), ()>(&mut store, "deallocate_memory")
            .context("Wasm module must export 'deallocate_memory' fn")?;

        let expand_schema_fn = instance
            .get_typed_func::<(u32, u32), u64>(&mut store, "expand_schema")
            .context("Wasm module must export 'expand_schema' fn")?;

        println!("Turn Macro Engine: Fetching remote schema payload from {} ...", target_url);
        let client = reqwest::Client::new();
        let payload = client.get(&target_url).send().await?.text().await?;
        let payload_bytes = payload.as_bytes();
        let payload_len = payload_bytes.len() as u32;

        // 1. Ask Wasm to allocate memory for the payload
        let payload_ptr = allocate.call(&mut store, payload_len)?;

        // 2. Write payload into Wasm memory
        memory.write(&mut store, payload_ptr as usize, payload_bytes)
            .context("Failed to write schema payload into Wasm memory")?;

        // 3. Call the macro
        let result_packed = expand_schema_fn.call(&mut store, (payload_ptr, payload_len))?;

        // 4. Decode the result pointer and length
        let result_len = (result_packed >> 32) as u32;
        let result_ptr = (result_packed & 0xFFFFFFFF) as u32;

        // 5. Read the AST JSON string from Wasm memory
        let mut result_bytes = vec![0u8; result_len as usize];
        memory.read(&store, result_ptr as usize, &mut result_bytes)
            .context("Failed to read generated AST from Wasm memory")?;

        let ast_json = String::from_utf8(result_bytes)
            .context("Macro returned invalid UTF-8")?;

        // 6. Free the memory inside Wasm
        deallocate.call(&mut store, (result_ptr, result_len))?;

        // 7. Deserialize JSON into Turn AST structure
        let stmts: Vec<Stmt> = serde_json::from_str(&ast_json)
            .context(format!("Macro returned invalid AST JSON: {}", ast_json))?;

        let turn_closure = Expr::Turn {
            is_tool: false,
            params: vec![],
            ret_ty: None,
            body: Block { stmts, span: span.clone() },
            span: span.clone(),
        };

        Ok(Expr::Call {
            name: Box::new(turn_closure),
            arg: Box::new(Expr::Literal {
                value: crate::ast::Literal::Null,
                span: span.clone(),
            }),
            span,
        })
    }
}
